workflows:
  smartassistant-ios-fixed:
    name: SmartAssistant iOS Fixed
    environment:
      groups:
        - ios_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Force iOS 15.0+ for Firebase
        script: |
          echo "=== FORCING iOS 15.0+ ==="
          
          # ✅ ELIMINAR y RECREAR Podfile completamente
          cd ios
          rm -f Podfile Podfile.lock
          
          # Crear nuevo Podfile con platform 15.0
          cat > Podfile << EOF
          # GENERATED FOR FIREBASE COMPATIBILITY
          platform :ios, '15.0'
          install! 'cocoapods', :deterministic_uuids => false
          
          target 'Runner' do
            use_frameworks!
            use_modular_headers!
            
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end
          
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
            end
          end
          EOF
          
          echo "✅ New Podfile created with iOS 15.0"
          cat Podfile
          cd ..
      
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
      
      - name: Pod install with force update
        script: |
          cd ios
          pod cache clean --all
          pod repo update
          pod install --repo-update --verbose
          cd ..
      
      - name: Build iOS
        script: |
          flutter build ipa --release --no-codesign
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      email:
        recipients:
          - miltonpinamoreno@email.com
        notify:
          success: true
          failure: true