workflows:
  smartassistant-android-fixed:
    name: SmartAssistant Android Fixed
    environment:
      groups:
        - android_credentials
      flutter: stable
      vars:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g"
        _JAVA_OPTIONS: "-Xmx4g"
    
    scripts:
      - name: Setup Java memory
        script: |
          echo "=== CONFIGURANDO MEMORIA JAVA ==="
          # Crear archivo de propiedades para Gradle
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" > android/gradle.properties
          echo "android.enableJetifier=false" >> android/gradle.properties
      
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
      
      - name: Build Android Release APK
        script: |
          echo "=== BUILDING RELEASE APK ==="
          flutter build apk --release --verbose
      
      - name: Build Android App Bundle
        script: |
          echo "=== BUILDING APP BUNDLE ==="
          flutter build appbundle --release --verbose
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/**/*.aab
    
    publishing:
      email:
        recipients:
          - miltonpinamoreno@gmail.com
        notify:
          success: true
          failure: true
