workflows:
  smartassistant-ios-beta:
    name: SmartAssistant iOS Beta
    environment:
      groups:
        - ios_credentials  # Para certificados de iOS
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set iOS deployment target
        script: |
          # ✅ SOLUCIÓN: Actualizar deployment target a 15.0
          echo "Updating iOS deployment target to 15.0..."
          
          # Actualizar Podfile
          cd ios
          if ! grep -q "platform :ios" Podfile; then
            echo "platform :ios, '15.0'" > Podfile
          else
            sed -i '' 's/platform :ios, .*/platform :ios, '\''15.0'\''/' Podfile
          fi
          
          # Actualizar Info.plist si es necesario
          cd ..
      
      - name: Get dependencies
        script: flutter pub get
      
      - name: Install iOS dependencies
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..
      
      - name: Build iOS
        script: flutter build ipa --release
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - miltonpinamoreno@email.com
        notify:
          success: true
          failure: true